name: Build & publish nerc-bootstrap images
on:
  release:
    types: [ published ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build.yaml"
      - "containers/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: base
            image: ghcr.io/nerc-project/nerc-bootstrap/base
          - container: dhcpd
            image: ghcr.io/nerc-project/nerc-bootstrap/dhcpd
          - container: tftpd
            image: ghcr.io/nerc-project/nerc-bootstrap/tftpd
          - container: httpd
            image: ghcr.io/nerc-project/nerc-bootstrap/httpd
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./containers/${{ matrix.container }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
